# Generated by Django 4.2.3 on 2023-08-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name_0',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Название цвета 0'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_0',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 0'),
        ),
    ]
