# Generated by Django 4.2.3 on 2023-08-17 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_color_name_0_product_image_0'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
