# Generated by Django 4.2.3 on 2023-08-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name_1',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Название цвета 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_2',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Название цвета 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_3',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Название цвета 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='color_name_4',
            field=models.CharField(blank=True, default=None, max_length=63, null=True, verbose_name='Название цвета 4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Изображение 4'),
        ),
    ]
