# Generated by Django 4.2.3 on 2023-08-18 08:07

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_color_name_1_product_color_name_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_0',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='color_1',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='color_2',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='color_3',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddField(
            model_name='product',
            name='color_4',
            field=colorfield.fields.ColorField(blank=True, default='#FFFFFF', image_field=None, max_length=18, null=True, samples=None),
        ),
    ]
